### ISSUE TITLE
OOM error in docker getmeili/meilisearch:latest 

### ISSUE THREAD

**Issue by rzakhanov** [meilisearch/meilisearch-php#379]
Hello. Why does Meilisearch service down after few seconds ? Giving error 137 (out of memory - docker doc.) 

Inside meili data.ms have 44.000 item and one index.

 This is content for meilisearch service :
```
meilisearch:
  container_name: meilisearch
  image: 'getmeili/meilisearch:latest'
  ports:
  - '7700:7700'
  volumes:
  - './Docker/meilisearch/volume/:/meili_data'
  networks:
  customnetwork:
  ipv4_address: 172.20.0.13
  healthcheck:
  test: ["CMD", "wget", "--no-verbose", "--spider",  "5"]
  retries: 3
  timeout: 5s
  deploy:
  resources:
  limits:
  memory: 6g
  reservations:
  memory: 5g
```
