### ISSUE TITLE
Laravel Scout - empty results

### ISSUE THREAD

**Issue by francoism90** [meilisearch/meilisearch-php#381]
**Description**
```json
"require": {
        "laravel/framework": "^9.31",
        "laravel/scout": "^9.4",
        "meilisearch/meilisearch-php": "^0.24.2",
    },
```

```php
User::search('*')->raw()
=> [
     "hits" => [
       [
         "email" => "bar@foo.com",
         "id" => "bar",
         "__soft_deleted" => 0,
       ],
     ],
     "estimatedTotalHits" => 1,
     "query" => "*",
     "limit" => 20,
     "offset" => 0,
     "processingTimeMs" => 0,
     "nbHits" => 1,
   ]
```

**Expected behavior**
Show me the collection/items.

**Current behavior**
```bash
User::search('*')->get()
=> Illuminate\Database\Eloquent\Collection {#5612
     all: [],
   }
```

**Screenshots or Logs**
If applicable, add screenshots or logs to help explain your problem.

**Environment (please complete the following information):**
```
meilisearch:
        image: 'getmeili/meilisearch:latest'
        ports:
            - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
        volumes:
            - 'sail-meilisearch:/data.ms'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "wget", "--no-verbose", "--spider",  "http://localhost:7700/health"]
            retries: 3
            timeout: 5s
```
I'm using Laravel Sail, it worked fine, but it seems to be broken on latest release. :/
