### ISSUE TITLE
Add new code-samples requested by the Meilisearch v0.29 release

### ISSUE THREAD

**Issue by brunoocasali** [meilisearch/meilisearch-php#403]
⚠️ This issue is generated, it means the examples and the namings do not necessarily correspond to the language of this repository.
Also, if you are a maintainer, please add any clarification and instructions about this issue.

Sorry if this is already wholly/partially implemented. Feel free to let me know about the state of this issue in the repo.

Related to https://github.com/meilisearch/integration-guides/issues/213

----

Add the new code samples into the file `.code-samples.meilisearch.yml`:

TODO:
- [ ] Add `search_parameter_guide_matching_strategy_1`
  - Search for `big fat liar` with `"matchingStrategy": "last"` in a `movies` index.
- [ ] Add `search_parameter_guide_matching_strategy_2`
  - Search for `big fat liar` with `"matchingStrategy": "all"` in a `movies` index.

For example, in Javascript, the code-samples required to fix the issue are:

`client.index('movies').search('big fat liar', { matchingStrategy: 'last' })` and also 
`client.index('movies').search('big fat liar', { matchingStrategy: 'all' })`

so the final version inside of the samples should be:

```yml
search_parameter_guide_matching_strategy_1: |-
  client.index('movies').search('big fat liar', { matchingStrategy: 'last' })
search_parameter_guide_matching_strategy_2: |-
  client.index('movies').search('big fat liar', { matchingStrategy: 'all' })
```
