### ISSUE TITLE
The provided API key is invalid

### ISSUE THREAD

**Issue by jackkitley** [meilisearch/meilisearch-php#576]
**Description**
Using meilisearch in docker V1.3.0 along with the same version of composer package. When i start indexing it throws this error even though i have a master key set.

**Expected behavior**
I expect it to index

**Current behavior**
threw "The provided API key is invalid"

**Screenshots or Logs**
```php
{
    "class": "Meilisearch\\Exceptions\\ApiException",
    "message": "The provided API key is invalid.",
    "code": 403,
    "file": "/var/www/html/vendor/meilisearch/meilisearch-php/src/Http/Client.php:186",
    "trace": [
        "/var/www/html/vendor/meilisearch/meilisearch-php/src/Http/Client.php:157",
        "/var/www/html/vendor/meilisearch/meilisearch-php/src/Http/Client.php:95",
        "/var/www/html/vendor/meilisearch/meilisearch-php/src/Endpoints/Delegates/HandlesDocuments.php:43",
        "/var/www/html/vendor/laravel/scout/src/Engines/MeilisearchEngine.php:75",
        "/var/www/html/vendor/laravel/scout/src/Jobs/MakeSearchable.php:42",
        "/var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:36",
```

```yaml
    meilisearch:
        container_name: meilisearch
        image: getmeili/meilisearch:v1.3
        environment:
            - http_proxy
            - https_proxy
            - MEILI_MASTER_KEY='MASTER_KEY'
            - MEILI_NO_ANALYTICS=${MEILI_NO_ANALYTICS:-true}
            - MEILI_ENV=${MEILI_ENV:-development}
            - MEILI_LOG_LEVEL
            - MEILI_DB_PATH=${MEILI_DB_PATH:-/data.ms}
        ports:
            - ${MEILI_PORT:-7700}:7700
        networks:
            - dealer_network
        volumes:
            - dd-meili:/data.ms
        restart: unless-stopped

```
![Screenshot 2023-09-07 at 12 09 33](https://github.com/meilisearch/meilisearch-php/assets/3243014/a6a8e13b-ef9a-4b76-b9c0-9775f375c25f)

**Environment (please complete the following information):**
- OS: OSX
- Meilisearch version: V1.3.0
- meilisearch-php version: 1.3.0
